name: GitHub Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          config_timezone: Asia/Calcutta

          template: classic
          
          base: header, activity, community, metadata
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_sections: most-used

          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 60

          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 30
